#!/usr/bin/env ruby

$:.unshift "#{__dir__}/../lib"

require "version"
require "ansi/string_view"
require "optparse"

OptionParser.new("Usage: #{File.basename($0)} [file ...]").parse!

table = ARGF.each_line.map { |l| l.chomp.split("\t").map { |cell| ANSI::StringView.new(cell).strip } }

return if table.empty?

width = table.map(&:size).max
column_widths = Array.new(width) { |i|
  table
    .map { |row| row[i] }
    .compact
    .map { |cell| ANSI::StringView.new(cell).length }
    .max
}

table.each do |row|
  puts row.zip(column_widths).map { |cell, width| ANSI::StringView.new(cell).ljust(width) }.join("  ")
end
